# Generated by Django 5.2.1 on 2025-05-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='img/', verbose_name='Imagen'),
        ),
    ]
